- name: Get cluster facts
  ovirt_clusters_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "name={{ cluster_name }}"
  check_mode: "no"

- name: Get name of the original scheduling policy
  ovirt_scheduling_policies_facts:
    auth: "{{ ovirt_auth }}"
    id: "{{ ovirt_clusters[0].scheduling_policy.id }}"
  check_mode: "no"

- name: Remember the cluster scheduling policy
  set_fact:
    cluster_scheduling_policy: "{{ ovirt_scheduling_policies[0].name }}"

- name: Get API facts
  ovirt_api_facts:
    auth: "{{ ovirt_auth }}"
  check_mode: "no"

- name: Set in cluster upgrade policy
  ovirt_clusters:
    auth: "{{ ovirt_auth }}"
    name: "{{ cluster_name }}"
    scheduling_policy: cluster_maintenance
  register: cluster_policy
  when:
    - (ovirt_api.product_info.version.major >= 4 and ovirt_api.product_info.version.major >= 2) or
      (ovirt_api.product_info.version.major == 4 and ovirt_api.product_info.version.major == 1 and ovirt_api.product_info.version.revision >= 4)
